name: Performance Regression Detection

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  detect-regressions:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build packages
      run: npm run build
    
    - name: Run benchmarks and detect regressions
      run: |
        cd packages/benchmark
        ./scripts/ci-regression-detection.sh
    
    - name: Upload regression report
      uses: actions/upload-artifact@v4
      with:
        name: regression-report
        path: packages/benchmark/reports/regression-report.md
        if-no-files-found: warn
